// RnDumb Fun - GameDev.TV Game Jam 2025

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace ContestantGameplayTags
{
	//**  Input Tags  **//
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_OpenLobby)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CallOpenLevel)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CallClientTravel)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CreateGameSession)
	TINYWORLDGAMESHOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_JoinGameSession)
}